-- The PostgreSQL schema is managed automatically by Flyway when Ktor starts.
-- Canonical migration:
-- server/src/main/resources/db/migration/V1__supportdesk_schema.sql
--
-- Do not apply this compatibility marker in the Supabase SQL editor. Start Ktor
-- with valid database credentials and review /health/ready instead.
